# Generated by Django 4.2.11 on 2024-04-19 04:29

from django.db import migrations, models
import servicerequests.models


class Migration(migrations.Migration):

    dependencies = [
        ("servicerequests", "0002_alter_servicerequest_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=servicerequests.models.attachment_upload_path,
            ),
        ),
    ]
